# GRAPHICS Files

set(GRAPHICS_INTERFACE_DIR ${ENGINE_RUNTIME_SOURCE_DIR}/GRAPHICS/Public)
set(GRAPHICS_SOURCE_DIR ${ENGINE_RUNTIME_SOURCE_DIR}/GRAPHICS/Private)


file(GLOB_RECURSE GRAPHICS_INTERFACE_FILES ${GRAPHICS_INTERFACE_DIR}/GRAPHICS/*.h ${GRAPHICS_INTERFACE_DIR}/GRAPHICS/*.hpp)
file(GLOB_RECURSE GRAPHICS_INCLUDE_FILES ${GRAPHICS_SOURCE_DIR}/*.h PREFIX "Header" ${GRAPHICS_SOURCE_DIR}/*.hpp)
file(GLOB_RECURSE GRAPHICS_SOURCE_FILES ${GRAPHICS_SOURCE_DIR}/*.cpp "Source" ${GRAPHICS_SOURCE_DIR}/**.c)

