#PROFILER Files

set(PROFILER_INTERFACE_DIR ${ENGINE_RUNTIME_SOURCE_DIR}/PROFILER/Public)
set(PROFILER_SOURCE_DIR ${ENGINE_RUNTIME_SOURCE_DIR}/PROFILER/Private)


file(GLOB_RECURSE PROFILER_INTERFACE_FILES ${PROFILER_INTERFACE_DIR}/PROFILER/*.h ${PROFILER_INTERFACE_DIR}/PROFILER/*.hpp)
file(GLOB_RECURSE PROFILER_INCLUDE_FILES ${PROFILER_SOURCE_DIR}/*.h PREFIX "Header" ${PROFILER_SOURCE_DIR}/*.hpp)
file(GLOB_RECURSE PROFILER_SOURCE_FILES ${PROFILER_SOURCE_DIR}/*.cpp "Source" ${PROFILER_SOURCE_DIR}/**.c)

